export default {
    BACK: {
        FULL: 'https://i.imgur.com/Ggu8xlE.png',
        HALF: 'https://i.imgur.com/4pqATmt.png',
        FIVE: 'https://i.imgur.com/fP9bL6O.png',
        FOUR: 'https://i.imgur.com/tPJcCL9.png',
        THREE: 'https://i.imgur.com/83dtG4X.png',
        TWO: 'https://i.imgur.com/zIQRKqa.png',
        ONE: 'https://i.imgur.com/TZJdpPC.png',
        DEFAULT: 'https://i.imgur.com/RO3DOEa.jpg'
    },
    FRONT: [
        'https://upload.wikimedia.org/wikipedia/commons/thumb/7/75/Minicard_AS.svg/155px-Minicard_AS.svg.png',
        'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1e/Minicard_2S.svg/155px-Minicard_2S.svg.png',
        'https://upload.wikimedia.org/wikipedia/commons/thumb/7/76/Minicard_3S.svg/155px-Minicard_3S.svg.png',
        'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Minicard_4S.svg/155px-Minicard_4S.svg.png',
        'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/Minicard_5S.svg/155px-Minicard_5S.svg.png',
        'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e7/Minicard_6S.svg/155px-Minicard_6S.svg.png',
        'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e8/Minicard_7S.svg/155px-Minicard_7S.svg.png',
        'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/Minicard_8S.svg/155px-Minicard_8S.svg.png',
        'https://upload.wikimedia.org/wikipedia/commons/thumb/4/40/Minicard_9S.svg/155px-Minicard_9S.svg.png',
        'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Minicard_10S.svg/155px-Minicard_10S.svg.png',
        'https://upload.wikimedia.org/wikipedia/commons/thumb/1/13/Minicard_JS.svg/155px-Minicard_JS.svg.png',
        'https://upload.wikimedia.org/wikipedia/commons/thumb/0/02/Minicard_QS.svg/155px-Minicard_QS.svg.png',
        'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Minicard_KS.svg/155px-Minicard_KS.svg.png',
        'https://upload.wikimedia.org/wikipedia/commons/thumb/7/75/Minicard_AH.svg/155px-Minicard_AH.svg.png',
        'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fb/Minicard_2H.svg/155px-Minicard_2H.svg.png',
        'https://upload.wikimedia.org/wikipedia/commons/thumb/7/75/Minicard_3H.svg/155px-Minicard_3H.svg.png',
        'https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Minicard_4H.svg/155px-Minicard_4H.svg.png',
        'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fb/Minicard_5H.svg/155px-Minicard_5H.svg.png',
        'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7e/Minicard_6H.svg/155px-Minicard_6H.svg.png',
        'https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Minicard_7H.svg/155px-Minicard_7H.svg.png',
        'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ae/Minicard_8H.svg/155px-Minicard_8H.svg.png',
        'https://upload.wikimedia.org/wikipedia/commons/thumb/9/94/Minicard_9H.svg/155px-Minicard_9H.svg.png',
        'https://upload.wikimedia.org/wikipedia/commons/thumb/1/15/Minicard_10H.svg/155px-Minicard_10H.svg.png',
        'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Minicard_JH.svg/155px-Minicard_JH.svg.png',
        'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Minicard_QH.svg/155px-Minicard_QH.svg.png',
        'https://upload.wikimedia.org/wikipedia/commons/thumb/d/dc/Minicard_KH.svg/155px-Minicard_KH.svg.png',
        'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c6/Minicard_AD.svg/155px-Minicard_AD.svg.png',
        'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e7/Minicard_2D.svg/155px-Minicard_2D.svg.png',
        'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e9/Minicard_3D.svg/155px-Minicard_3D.svg.png',
        'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e8/Minicard_4D.svg/155px-Minicard_4D.svg.png',
        'https://upload.wikimedia.org/wikipedia/commons/thumb/6/69/Minicard_5D.svg/155px-Minicard_5D.svg.png',
        'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cb/Minicard_6D.svg/155px-Minicard_6D.svg.png',
        'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cf/Minicard_7D.svg/155px-Minicard_7D.svg.png',
        'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ef/Minicard_8D.svg/155px-Minicard_8D.svg.png',
        'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Minicard_9D.svg/155px-Minicard_9D.svg.png',
        'https://upload.wikimedia.org/wikipedia/commons/thumb/a/af/Minicard_10D.svg/155px-Minicard_10D.svg.png',
        'https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/Minicard_JD.svg/155px-Minicard_JD.svg.png',
        'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Minicard_QD.svg/155px-Minicard_QD.svg.png',
        'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/Minicard_KD.svg/155px-Minicard_KD.svg.png',
        'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/Minicard_AC.svg/155px-Minicard_AC.svg.png',
        'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bb/Minicard_2C.svg/155px-Minicard_2C.svg.png',
        'https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/Minicard_3C.svg/155px-Minicard_3C.svg.png',
        'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a3/Minicard_4C.svg/155px-Minicard_4C.svg.png',
        'https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/Minicard_5C.svg/155px-Minicard_5C.svg.png',
        'https://upload.wikimedia.org/wikipedia/commons/thumb/3/30/Minicard_6C.svg/155px-Minicard_6C.svg.png',
        'https://upload.wikimedia.org/wikipedia/commons/thumb/9/96/Minicard_7C.svg/155px-Minicard_7C.svg.png',
        'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9b/Minicard_8C.svg/155px-Minicard_8C.svg.png',
        'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b2/Minicard_9C.svg/155px-Minicard_9C.svg.png',
        'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Minicard_10C.svg/155px-Minicard_10C.svg.png',
        'https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/Minicard_JC.svg/155px-Minicard_JC.svg.png',
        'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bf/Minicard_QC.svg/155px-Minicard_QC.svg.png',
        'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Minicard_KC.svg/155px-Minicard_KC.svg.png'
    ]
};

